Sdg selector limit
AngelProtocolFinance/angelprotocol-web-app pull request #1838
Opened 2023-02-21 08:29 UTC by abbasali1994

Ticket(s):
-

## Explanation of the solution

## Instructions on making this work

- run `yarn` or `yarn install` to install npm dependencies
- run `yarn run test --watchAll` to verify all tests still pass
- (optional) run `yarn run build` to verify the build passes
- run `yarn start` to start the webapp
-

## UI changes for review
![image](https://user-images.githubusercontent.com/23124046/220289895-7a9e6eb8-34f9-4601-b7cd-3ca351c1cc95.png)

2023-02-21 09:15 UTC, misicnenad commented
@abbasali1994 please update description to include a link to the appropriate ticket, so we can verify the requirements.

2023-02-21 10:22 UTC, ap-justin commented
@abbasali1994, is it required to show error on `modal`  ?  I believe `max` could just be set on form's schema

2023-02-22 05:52 UTC, misicnenad requested changes
@abbasali1994 extending on what @ap-justin had said, you can implement the relevant task with a one-line change by just going to [src/pages/Admin/Charity/EditProfile/schema.ts](https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/79e61e8e9829fcd5be02ad4f8a8276bfd20c60bb/src/pages/Admin/Charity/EditProfile/schema.ts#L25) and updating the `categories_sdgs` schema by adding `.max(8, "maximum 8 selections allowed")` to it, so full code would be:
```ts
categories_sdgs: Yup.array().min(1, "required").max(8, "maximum 8 selections allowed") // or some different error message
```

2023-02-22 06:50 UTC, SovereignAndrey approved these changes

2023-02-22 09:23 UTC, misicnenad approved these changes

2023-02-22 09:32 UTC, merged