move Logo component to common components
AngelProtocolFinance/angelprotocol-web-app pull request #1849
Opened 2023-02-22 13:36 UTC by abbasali1994

Ticket(s):
- closes [#1826](https://github.com/AngelProtocolFinance/angelprotocol-web-app/issues/1826)

## Explanation of the solution

## Instructions on making this work

- run `yarn` or `yarn install` to install npm dependencies
- run `yarn run test --watchAll` to verify all tests still pass
- (optional) run `yarn run build` to verify the build passes
- run `yarn start` to start the webapp
-

## UI changes for review

When major UI changes are introduced with a PR, please include links to URLS to compare or screenshots demonstrating the difference and notify on design changes

2023-02-22 13:37 UTC, abbasali1994 commented
@misicnenad @ap-justin can this <Logo /> be used with Marketplace cards as well?

2023-02-23 05:59 UTC, misicnenad commented
> @misicnenad @ap-justin can this be used with Marketplace cards as well?

@abbasali1994 yes it could, it could be renamed to `Image` to be used for general image loading/display.

2023-02-23 06:00 UTC, misicnenad requested changes
There are a bunch of other `Logo.tsx` files/components, all (most) of them should be using this common one.

2023-02-27 07:32 UTC, misicnenad requested changes
There are other Logo's that can be replaced with the newly created `Image`:
`src/pages/Profile/Logo.tsx`
`src/App/Header/Logo.tsx`
`src/components/APLogo.tsx`

Also, [LogoPlaceholder](https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/master/src/components/LogoPlaceholder.tsx) is used only in `Image` and should be renamed to `ImagePlaceholder`.

2023-02-27 07:32 UTC, misicnenad commented on src/components/WalletSuite/WalletSelectorOpener/Connector.tsx
> +      <Image src={props.logo} className={"w-12 h-12"} />
nit: no need for surrounding curly brackets, `...={"..."}` can be just `...="..."`

2023-03-06 17:37 UTC, misicnenad commented
> There are other Logo's that can be replaced with the newly created `Image`: `src/pages/Profile/Logo.tsx` `src/App/Header/Logo.tsx` `src/components/APLogo.tsx`
> 
> Also, [LogoPlaceholder](https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/master/src/components/LogoPlaceholder.tsx) is used only in `Image` and should be renamed to `ImagePlaceholder`.

@SovereignAndrey @abbasali1994 @ap-justin addressed remaining change requests.

In light of changes introduced in this PR, it would make sense to replace all uses of plain `<img>` tags with this new general `Image` component as it is more powerful (supports loading logic+UI & placeholder images). Created a draft task proposal for this https://github.com/orgs/AngelProtocolFinance/projects/2/views/1?filterQuery=components%2F&pane=issue&itemId=22174640

2023-03-08 02:27 UTC, SovereignAndrey approved these changes

2023-03-08 02:27 UTC, merged