Giftcard fixes
AngelProtocolFinance/angelprotocol-web-app pull request #1871
Opened 2023-02-27 10:29 UTC by abbasali1994

Ticket(s):
- [1.7.1 testing - gift cards#1833](https://github.com/AngelProtocolFinance/angelprotocol-web-app/issues/1833)

## Explanation of the solution

## Instructions on making this work

- run `yarn` or `yarn install` to install npm dependencies
- run `yarn run test --watchAll` to verify all tests still pass
- (optional) run `yarn run build` to verify the build passes
- run `yarn start` to start the webapp
-

## UI changes for review

When major UI changes are introduced with a PR, please include links to URLS to compare or screenshots demonstrating the difference and notify on design changes

2023-02-27 12:50 UTC, ap-justin requested changes

2023-02-27 12:50 UTC, ap-justin commented on src/pages/Gift/Mailer/Form.tsx
>    const { handleSubmit, reset } = useFormContext<FV>();
```suggestion
  const { handleSubmit, reset, formState:{ isSubmitting } } = useFormContext<FV>();
```
you could use this state unless there's a reason for separate `isSending` state ?

2023-02-27 12:57 UTC, misicnenad requested changes
Is the issue with the tx estimation error solved now (see [Tim's comment](https://app.clickup.com/t/8677d7yzw?comment=90100005598414))?

Also, one of the requirements from the attached Loom video (see [CU task description](https://app.clickup.com/t/8677d7yzw)) was that after the "Send Giftcard" submit btn click, the user gets navigated away from the page - we should confirm which page that should be.

2023-02-27 12:57 UTC, misicnenad commented on src/pages/Gift/Purchase/Result/Success.tsx
> +        to={`${routes.mail}`}
nit: ``to={`${routes.mail}`}`` can be changed to `to={routes.mail}`

2023-02-28 07:09 UTC, abbasali1994 commented
Waiting for Tim to provide confirmation on which page to redirect after closing prompt

2023-03-01 00:25 UTC, SovereignAndrey commented
> Waiting for Tim to provide confirmation on which page to redirect after closing prompt

I believe he commented that the Marketplace page would be the redirect destination.

2023-03-08 08:28 UTC, misicnenad commented
@SovereignAndrey @abbasali1994 @ap-justin created a new "Successful sending of gift code" component in accordance with the new requirements ([link to Lambert's comment](https://app.clickup.com/t/8677d7yzw?comment=90050006800184&threadedComment=90030010700631)).

The email format request should be handled on AWS side @jp-mariano

2023-03-08 12:53 UTC, ap-justin approved these changes

2023-03-10 07:09 UTC, merged