Removed the duplicate "Crop" button
AngelProtocolFinance/angelprotocol-web-app pull request #1985
Opened 2023-03-24 06:42 UTC by satishkumarsajjan

Ticket(s):
-

## Explanation of the solution
There was a duplicate Crop button being displayed on the image because of copy pasting same button twice in the code. I removed the duplicate one.

## Instructions on making this work

- run `yarn` or `yarn install` to install npm dependencies
- run `yarn run test --watchAll` to verify all tests still pass
- (optional) run `yarn run build` to verify the build passes
- run `yarn start` to start the webapp
-

## UI changes for review

When major UI changes are introduced with a PR, please include links to URLS to compare or screenshots demonstrating the difference and notify on design changes

2023-03-24 07:16 UTC, satishkumarsajjan commented
Fixes #1982

2023-03-24 07:38 UTC, ap-justin requested changes

2023-03-24 07:38 UTC, ap-justin commented on src/components/WalletSuite/ConnectedWallet/Details/MyEndowments/MyEndowments.tsx
> +      <div className="overflow-y-auto max-h-40 grid gap-3">
```suggestion
      <div className="overflow-y-auto max-h-40 scroller grid gap-3">
```
@satishkumarsajjan, nice work🥇 
we should not remove `scroller` as it is needed when the list gets long
* #1968

2023-03-27 02:54 UTC, SovereignAndrey commented on src/components/ImgEditor/ImgEditor.tsx
> +
```suggestion
```

2023-03-27 03:14 UTC, ap-justin approved these changes

2023-03-27 04:49 UTC, SovereignAndrey approved these changes

2023-03-27 04:49 UTC, merged