Fix Contibutions UI wording
AngelProtocolFinance/angelprotocol-web-app pull request #2134
Opened 2023-05-03 04:20 UTC by abbasali1994

Ticket(s):
- https://app.clickup.com/t/860qqg78m
- https://app.clickup.com/t/860qqga5x
- https://app.clickup.com/t/860qqgae1

## Explanation of the solution

## Instructions on making this work

- run `yarn` or `yarn install` to install npm dependencies
- run `yarn run test --watchAll` to verify all tests still pass
- (optional) run `yarn run build` to verify the build passes
- run `yarn start` to start the webapp
-

## UI changes for review

When major UI changes are introduced with a PR, please include links to URLS to compare or screenshots demonstrating the difference and notify on design changes

2023-05-03 05:04 UTC, ap-justin approved these changes

2023-05-03 23:09 UTC, SovereignAndrey requested changes
Nice work with this clean up of wordings. There's one component I left a comment on that needs a change. Thanks!

2023-05-03 23:09 UTC, SovereignAndrey commented on src/pages/Admin/Charity/DonationsTable/DonationsTable.tsx
> +          loading: "Fetching contributions..",
@abbasali1994 We should use PAYMENT_WORDS here in this component too. Otherwise the Charity app will show 'contribution(s)' and not 'donation(s)'

2023-05-04 08:24 UTC, SovereignAndrey submitted a review, later dismissed

2023-05-04 08:51 UTC, SovereignAndrey approved these changes

2023-05-04 08:55 UTC, merged