make launchpad steps clicakble
AngelProtocolFinance/angelprotocol-web-app pull request #2142
Opened 2023-05-04 09:58 UTC by abbasali1994

Ticket(s):
- https://app.clickup.com/t/860qqqq4t

## Explanation of the solution

## Instructions on making this work

- run `yarn` or `yarn install` to install npm dependencies
- run `yarn run test --watchAll` to verify all tests still pass
- (optional) run `yarn run build` to verify the build passes
- run `yarn start` to start the webapp
-

## UI changes for review

When major UI changes are introduced with a PR, please include links to URLS to compare or screenshots demonstrating the difference and notify on design changes

2023-05-04 12:22 UTC, ap-justin requested changes

2023-05-04 12:22 UTC, ap-justin commented on src/pages/Launchpad/Progress.tsx
> +        <Link
according to ticket, link only works if `isDone` - though there's a check that redirects back to latest progress, its purpose is to guard users from inputing `step` directly from url

2023-05-04 12:22 UTC, ap-justin commented on src/pages/Launchpad/Progress.tsx
> +          <Step isDone={p >= 2} isCurr={step === 2} step={steps[2]}>
you could map `<Step/>` by creating an array/object of step titles

also, `isDone` and `isCurr` is better computed inside `<Step/>` now that `step` is passed as props

2023-05-06 00:57 UTC, SovereignAndrey approved these changes

2023-05-06 00:58 UTC, merged