Refetch profile data on update
AngelProtocolFinance/angelprotocol-web-app pull request #2173
Opened 2023-05-10 12:44 UTC by abbasali1994

Ticket(s):
- [Wallet details not updated to reflect a new AST creation#2151](https://github.com/AngelProtocolFinance/angelprotocol-web-app/issues/2151)

## Explanation of the solution

## Instructions on making this work

- run `yarn` or `yarn install` to install npm dependencies
- run `yarn run test --watchAll` to verify all tests still pass
- (optional) run `yarn run build` to verify the build passes
- run `yarn start` to start the webapp
-

## UI changes for review

When major UI changes are introduced with a PR, please include links to URLS to compare or screenshots demonstrating the difference and notify on design changes

2023-05-10 14:25 UTC, ap-justin requested changes

2023-05-12 05:48 UTC, abbasali1994 commented on src/components/WalletSuite/ConnectedWallet/Details/index.tsx
> +    refetchOnFocus: true,
i will check to it

2023-05-12 05:55 UTC, abbasali1994 commented on src/components/WalletSuite/ConnectedWallet/Details/index.tsx
> +    refetchOnFocus: true,
Done

2023-05-12 06:31 UTC, SovereignAndrey approved these changes

2023-05-12 06:31 UTC, merged