navbar full width, not rounded, and always @ top
AngelProtocolFinance/angelprotocol-web-app pull request #2740
Opened 2024-02-20 06:28 UTC by SovereignAndrey

## Explanation of the solution
Addresses more changes requested for NavBar:
- not rounded 
- full width
- at the top of the screen

## Instructions on making this work

- run `yarn` or `yarn install` to install npm dependencies
- run `yarn run test --watchAll` to verify all tests still pass
- (optional) run `yarn run build` to verify the build passes
- run `yarn start` to start the webapp
-

## UI changes for review

When major UI changes are introduced with a PR, please include links to URLS to compare or screenshots demonstrating the difference and notify on design changes

2024-02-20 10:06 UTC, misicnenad requested changes

2024-02-21 03:34 UTC, SovereignAndrey commented on src/App/Header/useHeaderClassNames.ts
>        ? "fixed top-0 shadow-lg bg-white dark:bg-blue-d3"
I _think_ I got them all. Ignored un-used pages like giftcards/leaderboard for now. We can address those if/when they get worked on. See: f6b365fa2

2024-02-21 07:05 UTC, misicnenad requested changes
Other than the absolute-positioning-related comment, all are nits

2024-02-21 07:05 UTC, misicnenad commented on src/App/Header/useHeaderClassNames.ts
>    return `${
Dependence on absolute positioning should be removed to allow the header to become part of the grid structure, so this whole return can be rewritten to:
```ts
  return `${
    isScrolled ? "shadow-lg" : ""
  } transition ease-in-out duration-100 z-20 w-full`;
```

2024-02-21 07:27 UTC, merged